export const CHECKBOX_TOGGLE = 'CHECKBOX_TOGGLE';
// ACTION INPUT VALUE
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const CHANGE_INPUT_VALUE_ACCOUNT = 'CHANGE_INPUT_VALUE_ACCOUNT';
export const SET_ERROR_PASSWORD = 'SET_ERROR_PASSWORD';
export const SET_SUCCESS_PASSWORD = 'SET_SUCCESS_PASSWORD';
// ACTION INPUT OFFERS
export const CHANGE_INPUT_VALUE_OFFERS = 'CHANGE_INPUT_VALUE_OFFERS';
export const TOGGLE_ONLINE_OFFER = 'TOGGLE_ONLINE_OFFER';
// ACTION INPUT RESEARCH
export const CHANGE_INPUT_VALUE_SIGNIN = 'CHANGE_INPUT_VALUE_SIGNIN';
export const CHANGE_INPUT_VALUE_SIGNUP = 'CHANGE_INPUT_VALUE_SIGNUP';
export const CHANGE_INPUT_VALUE_SEARCH = 'CHANGE_INPUT_VALUE_SEARCH';
export const CHANGE_INPUT_TIME_VALUE = 'CHANGE_INPUT_TIME_VALUE';
export const CHANGE_INPUT_MILES_VALUE = 'CHANGE_INPUT_MILES_VALUE';
export const CHANGE_INPUT_TRANS_VALUE = 'CHANGE_INPUT_TRANS_VALUE';
export const CHANGE_RADIO_BUTTON = 'CHANGE_RADIO_BUTTON';
export const CHANGE_CURRENT_POS = 'CHANGE_CURRENT_POS';
export const PRINT_SUGGESTIONS_ADRESS = 'PRINT_SUGGESTIONS_ADRESS';
export const SET_SUGGESTION_VALUE = 'SET_SUGGESTION_VALUE';
// ACTION MODAL
export const TOGGLE_PRINT_MODAL = 'TOGGLE_PRINT_MODAL';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';
export const TOGGLE_OPEN_SLIDE = 'TOGGLE_OPEN_SLIDE';
// ACTION USER TOKEN
export const GET_USER_TOKEN = 'GET_USER_TOKEN';
export const GET_USER_TOKEN_SUCCESS = 'GET_USER_TOKEN_SUCCESS';
export const GET_USER_TOKEN_ERROR = 'GET_USER_TOKEN_ERROR';
// ACTION API
export const GET_DATAS_FROM_API = 'GET_DATAS_FROM_API';
export const GET_DATAS_FROM_API_SUCCESS = 'GET_DATAS_FROM_API_SUCCESS';
export const GET_DATAS_FROM_API_ERROR = 'GET_DATAS_FROM_API_ERROR';
export const GET_ISOCHRONE = 'GET_ISOCHRONE';
export const GET_ISOCHRONE_SUCCESS = 'GET_ISOCHRONE_SUCCESS';
export const GET_ISOCHRONE_ERROR = 'GET_ISOCHRONE_ERROR';
export const SET_SUGGESTIONS_ADRESS = 'SET_SUGGESTIONS_ADRESS';
export const GET_DATA_AIR_POLLUTION = 'GET_DATA_AIR_POLLUTION';
export const GET_DATA_AIR_POLLUTION_SUCCESS = 'GET_DATA_AIR_POLLUTION_SUCCESS';
export const GET_DATA_AIR_POLLUTION_ERROR = 'GET_DATA_AIR_POLLUTION_ERROR';


// ACTION TOGGLE PHONE MAP COMPONENT
export const TOGGLE_OPEN_EXPLORE_SLIDE = 'TOGGLE_OPEN_EXPLORE_SLIDE';
// Action DomSETTINGS
export const TOGGLE_PRINT_EXPLORE_SEARCH = 'TOGGLE_PRINT_EXPLORE_SEARCH';
// Create USER
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
// ACTION MAP
export const STORE_MAP_REF = 'STORE_MAP_REF';
