export const CHECKBOX_TOGGLE = 'CHECKBOX_TOGGLE';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const CHANGE_INPUT_VALUE_ACCOUNT = 'CHANGE_INPUT_VALUE_ACCOUNT';

export const CHANGE_INPUT_TIME_VALUE = 'CHANGE_INPUT_TIME_VALUE';
export const CHANGE_INPUT_MILES_VALUE = 'CHANGE_INPUT_MILES_VALUE';
export const CHANGE_INPUT_TRANS_VALUE = 'CHANGE_INPUT_TRANS_VALUE';
export const CHANGE_RADIO_BUTTON = 'CHANGE_RADIO_BUTTON';
export const CHANGE_CURRENT_POS = 'CHANGE_CURRENT_POS';

export const TOGGLE_PRINT_MODAL = 'TOGGLE_PRINT_MODAL';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';
export const TOGGLE_OPEN_SLIDE = 'TOGGLE_OPEN_SLIDE';
