export const CHECKBOX_TOGGLE = 'CHECKBOX_TOGGLE';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const TOGGLE_PRINT_MODAL = 'TOGGLE_PRINT_MODAL';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';
export const TOGGLE_OPEN_SLIDE = 'TOGGLE_OPEN_SLIDE';
export const GET_USER_TOKEN = 'GET_USER_TOKEN';
export const GET_USER_TOKEN_SUCCESS = 'GET_USER_TOKEN_SUCCESS';
export const GET_USER_TOKEN_ERROR = 'GET_USER_TOKEN_ERROR';
